name:  oplus-resukisu-vring-snapdragon

on:
  workflow_dispatch:  # This allows this workflow to be called from another workflow


jobs:
  vring-resukisu-snapdragon:
    name: "${{ matrix.file }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - file: oneplus_10_pro_v
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_10_pro_b
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_10t_v
            kpm: true
            sched: false
            ipv6: true
          #- file: oneplus_11r_v
          #  kpm: true
          #  sched: false
          #  ipv6: true
          - file: oneplus_ace2_v
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace2_b
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace_pro_v
            kpm: true
            sched: false
            ipv6: true
          - file: oneplus_11_v
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_11_b
            kpm: true
            sched: false
            ipv6: true
          #- file: oneplus_12r_v
          #  kpm: true
          #  sched: false
          #  ipv6: true
          #- file: oneplus_12r_b
          #  kpm: true
          #  sched: false
          #  ipv6: true
          - file: oneplus_ace2_pro_v
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace2_pro_b
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace3_v
            kpm: true
            sched: false
            ipv6: true
          - file: oneplus_ace3_b
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace3_300_b
            kpm: true
            sched: false
            ipv6: true


          - file: oneplus_ace_3v_v
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace_3v_b
            kpm: true
            sched: false
            ipv6: true


          - file: oneplus_12_v
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_12_b
            kpm: true
            sched: false
            ipv6: true

          #- file: oneplus_13r
          #  kpm: true
          #  sched: false
          #  ipv6: true
          #- file: oneplus_13r_b
          #  kpm: true
          #  sched: false
          #  ipv6: true

          - file: oneplus_ace3_pro_v
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace3_pro
            kpm: true
            sched: false
            ipv6: true
          - file: oneplus_ace3_pro_b
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace5
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace5_b
            kpm: true
            sched: false
            ipv6: true


          - file: oneplus_pad_pro
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_pad_pro_v
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_pad_pro_b
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_pad2_v
            kpm: true
            sched: false
            ipv6: true
          - file: oneplus_pad2_b
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace5_pro
            kpm: true
            sched: true
            ipv6: true

          - file: oneplus_ace5_pro_b
            kpm: true
            sched: true
            ipv6: true





          - file: oneplus_pad_2_pro
            kpm: true
            sched: true
            ipv6: true

          - file: oneplus_pad_2_pro_b
            kpm: true
            sched: true
            ipv6: true

          - file: oneplus_13
            kpm: true
            sched: true
            ipv6: true

          - file: oneplus_13_b
            kpm: true
            sched: true
            ipv6: true


          - file: oneplus_13t
            kpm: true
            sched: true
            ipv6: true

          - file: oneplus_13t_b
            kpm: true
            sched: true
            ipv6: true


          #- file: oneplus_13s
          #  kpm: true
          #  sched: true
          #  ipv6: true

          #- file: oneplus_13s_b
          #  kpm: true
          #  sched: true
          #  ipv6: true

          - file: oneplus_pad_3
            kpm: true
            sched: true
            ipv6: true

          - file: oneplus_pad_3_b
            kpm: true
            sched: true
            ipv6: true

          - file: oneplus_ace_6
            kpm: true
            sched: true
            ipv6: true

          - file: oneplus_turbo_6v
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_turbo_6
            kpm: true
            sched: true
            ipv6: true

          - file: oneplus_ace_6t_Canary
            kpm: true
            sched: false
            ipv6: true
          - file: oneplus_15_Canary
            kpm: true
            sched: false
            ipv6: true
          - file: oneplus_15t_Canary
            kpm: true
            sched: false
            ipv6: true
          - file: oneplus_pad_4_Canary
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_pad_3_pro_Canary
            kpm: true
            sched: false
            ipv6: true


    uses: ./.github/workflows/build-kernel-original-make.yml
    secrets: inherit
    with:
      FILE: ${{ matrix.file }}
      HOOK: "manual"
      SUSFS_CI: "CI"
      KSU_META: "susfs-main/vring/"
      BUILD_TIME:  "Mon Aug 18 09:30:24 UTC 2024"
      SCHED: ${{ matrix.sched }}
      ZRAM: false
      LSM: true
      FAST_BUILD: true
      KPM: ${{ matrix.kpm }}
      IPV6: ${{ matrix.ipv6 }}
