name: oplus-resukisu-vring-5.15

on:
  workflow_dispatch:  # This allows this workflow to be called from another workflow


jobs:
  vring-resukisu:
    strategy:
      fail-fast: false
      matrix:
        include:



          #          #5.15
          - file: oneplus_ace3_v
            kpm: true
            sched: false
            ipv6: true
          - file: oneplus_ace3_b
            kpm: true
            sched: false
            ipv6: true


          #5.15
          - file: oneplus_12r_v
            kpm: true
            sched: false
            ipv6: true
          - file: oneplus_12r_b
            kpm: true
            sched: false
            ipv6: true



          #5.15
          - file: oneplus_11_v
            kpm: true
            sched: false
            ipv6: true
          - file: oneplus_11_b
            kpm: true
            sched: false
            ipv6: true

          #5.15
          - file: oneplus_ace2_pro_v
            kpm: true
            sched: false
            ipv6: true

          - file: oneplus_ace2_pro_b
            kpm: true
            sched: false
            ipv6: true


    uses: ./.github/workflows/build-kernel.yml
    secrets: inherit
    with:
      FILE: ${{ matrix.file }}
      HOOK: "manual"
      SUSFS_CI: "CI"
      KSU_META: "susfs-main/vring/"
      BUILD_TIME:  "Mon Aug 18 09:30:24 UTC 2024"
      SCHED: ${{ matrix.sched }}
      ZRAM: false
      LSM: true
      FAST_BUILD: true
      KPM: ${{ matrix.kpm }}
      IPV6: ${{ matrix.ipv6 }}