name:  Build一加RESUKISU@vring

on:
  workflow_dispatch:  # This allows this workflow to be called from another workflow


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:

          - file: oneplus_ace_v
            kpm: true
            sched: false
            ipv6: false
          - file: oneplus_ace_v
            kpm: false
            sched: false
            ipv6: false
          - file: oneplus_ace_u
            kpm: true
            sched: false
            ipv6: false
          - file: oneplus_ace_u
            kpm: false
            sched: false
            ipv6: false


          #acerate
          - file: oneplus_ace_race_v
            kpm: true
            sched: false
            ipv6: false
          - file: oneplus_ace_race_v
            kpm: false
            sched: false
            ipv6: false

          - file: oneplus_ace_race_u
            kpm: true
            sched: false
            ipv6: false
          - file: oneplus_ace_race_u
            kpm: false
            sched: false
            ipv6: false

          #ace22v
          - file: oneplus_ace_2v_v
            kpm: true
            sched: false
            ipv6: false
          - file: oneplus_ace_2v_v
            kpm: false
            sched: false
            ipv6: false
          - file: oneplus_ace_2v_b
            kpm: true
            sched: false
            ipv6: false
          - file: oneplus_ace_2v_b
            kpm: false
            sched: false
            ipv6: false


          - file: oneplus_ace5_race_b
            kpm: true
            sched: false
            ipv6: false

          - file: oneplus_ace5_race_v
            kpm: true
            sched: false
            ipv6: false

          - file: oneplus_ace5_ultra_b
            kpm: true
            sched: false
            ipv6: false

          - file: oneplus_ace5_ultra
            kpm: true
            sched: true
            ipv6: false

          - file: oneplus_ace5_ultra_b_vring
            kpm: true
            sched: true
            ipv6: false

          - file: oneplus_pad2_mt6991_b
            kpm: true
            sched: true
            ipv6: false
          #新增2026.03.28

          - file: oneplus_pad_mt6897_b
            kpm: true
            sched: true
            ipv6: false

          - file: oneplus_pad_mt6897_v
            kpm: true
            sched: true
            ipv6: false

#          - file: oneplus_15
#            kpm: true
#            sched: true
#          - file: oneplus_15_vring
#            kpm: true
#            sched: false

    uses: ./.github/workflows/build-kernel.yml
    secrets: inherit
    with:
      FILE: ${{ matrix.file }}
      HOOK: "manual"
      SUSFS_CI: "CI"
      KSU_META: "susfs-main/vring/"
      BUILD_TIME:  "Mon Aug 18 09:30:24 UTC 2024"
      SCHED: ${{ matrix.sched }}
      ZRAM: false
      LSM: true
      FAST_BUILD: true
      KPM: ${{ matrix.kpm }}
      IPV6: ${{ matrix.ipv6 }}